version: '3.1'
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: review_wongnai
      MYSQL_USER: root
      MYSQL_PASSWORD: root1234
    ports: 
      - 3307:3306
    volumes:
      - db-data:/var/lib/mysql

  web:
    # build: ./front-end
    image: taomju/node-web-app
    container_name: node-web-app
    ports:
      - 5000:5000
    depends_on:
      - api
      
  api:
    image: 'taomju/review-test-wongnai'
    # build: .
    restart: always
    ports:
      - "5555:5555"
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/review_wongnai?autoReconnect=true&useSSL=false
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root1234
    depends_on: 
      - db
    links:
      - db
volumes:
  db-data:
    driver: local